services:
  db:
    image: postgres:14
    restart: always
    ports:
      - "${HOST_PORT:-5432}:5432"

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-db-network
networks:
  app-db-network:
    driver: bridge

volumes:
  postgres-data: