server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  servlet:
    session:
      timeout: 20m

spring:
  application:
    name: sporty-api
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem:sportydb;MODE=PostgreSQL;DB_CLOSE_DELAY=0
    driver-class-name: org.h2.Driver
    username: sa
    password:
  flyway:
    enabled: true
    locations: classpath:db/migrations
  session:
    timeout: 20m
  mvc:
    view:
      prefix: none
  throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

logging:
  level:
    org.springframework.security: ERROR
    org.hibernate.resource.transaction: INFO
  config: classpath:logback.xml

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
    build:
      enabled: true